import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ClerkProvider } from '@clerk/nextjs';
import "./globals.css";

// Configure default sans-serif font
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

// Configure default monospace font
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

/**
 * Global Next.js metadata configuring document title, description, and SEO properties.
 */
export const metadata: Metadata = {
  title: "VersaDocs",
  description: "Generated by create next app",
};

/**
 * RootLayout - The foundational App Router layout wrapper.
 * Wraps the entire application in the `ClerkProvider` for authentication state management
 * and applies the base fonts and CSS reset to the `<html>` and `<body>` tags.
 */
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <ClerkProvider afterSignOutUrl="/">
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          {children}
        </body>
      </html>
    </ClerkProvider>
  )
}